sheet_csv_aventurier: "https://docs.google.com/spreadsheets/d/1HSNcznZFiA7flg2MuSKy8tS_aDLa-VdJjyFvvq4ya0s/export?format=csv&id=1HSNcznZFiA7flg2MuSKy8tS_aDLa-VdJjyFvvq4ya0s&gid=0"
sheet_csv_castors: "https://docs.google.com/spreadsheets/d/1HSNcznZFiA7flg2MuSKy8tS_aDLa-VdJjyFvvq4ya0s/export?format=csv&id=1HSNcznZFiA7flg2MuSKy8tS_aDLa-VdJjyFvvq4ya0s&gid=1288659161"
timezone: "America/Toronto"
